# 1. pg_dw = Stores data from ETL
# 2. pg_metabase = DB for metabase
# 3. metabase container

version: '3.9'
services:
  pg_dw:
    image: postgres:latest
    container_name: pg_dw
    hostname: pg_dw
    environment:
      POSTGRES_USER: MercuryDBA
      POSTGRES_DB: MercuryDW
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mercury_net
    ports:
      - 5432:5432

  pg_metabase:
    image: postgres:latest
    container_name: pg_metabase
    hostname: pg_metabase
    environment:
      POSTGRES_USER: MercuryDBA
      POSTGRES_DB: MetabaseDB
      POSTGRES_PASSWORD: password
    volumes:
      - pg_metabase_data:/var/lib/postgresql/data
    networks:
      - mercury_net
    ports:
      - 5434:5432

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: MetabaseDB
      MB_DB_PORT: 5432
      MB_DB_USER: MercuryDBA
      MB_DB_PASS: password
      MB_DB_HOST: pg_metabase
    volumes:
      - metabase_data:/metabase-data
    networks:
      - mercury_net
    ports:
      - 3030:3000

volumes:
  pg_data:
  pg_metabase_data:
  metabase_data:

networks:
  mercury_net:
    driver: bridge